### ISSUE TITLE
Why not all class methods?

### ISSUE THREAD

**Issue by neves** [tomdalling/pure-function-as-an-object#1]
What would be the odds of writing everything as class methods, like convert?

**Comment by tomdalling** [comment]
It's certainly an option, but it has a few drawbacks:
1. You have to pass arguments everywhere. For example, if the function takes a hash of options, that hash needs to be passed to all the other methods, often multiple levels deep into the call stack. It's sometimes more convenient to access those values as instance variables.
2. Memoization becomes harder. If a method takes no arguments because it's using instance variables, it's easy to memoize the return value as an instance variable. Also, once the object is garbage collected, all the memoized values get collected too. When you're passing things in as arguments, as you would with class methods, you can't memoize a single return value because the return value changes based on the arguments, so you have to make a memoization cache that stores return values by the arguments. Then you have to think about whether the cache will grow out of control, because it will never be garbage collected.

For small task it's better just to use class methods. However, for larger tasks with lots of methods that require access to state (like an options hash), using the "function as an object" pattern cleans the code up a bit.

**Comment by neves** [comment]
Thanks, that was clarifying
